

export const get_array_of_colum_width = () => {
    return [
        { width: 14.43 }, 
        { width: 17 }, 
        { width: 15.43 },
        { width: 8.29 },
        { width: 14.86 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 4.8 },
        { width: 9.3 },
        { width: 9.6 },
    ];
}