// icon-cancel-2
// fa-calendar
// icon-plus-1
// icon-search-4
// 'icon-plus'

// icon-download-alt
// icon-tools
// icon-edit
// icon-buffer
// icon-ellipsis-vert
// icon-clipboard-1
// fa-cube
// fa-cubes
// fa-navicon
// icon-floppy
// icon-params
// fa-list-ul
// icon-down-open-1
// icon-up-open-1
// icon-grid
// icon-ok-3
// icon-scissors
// icon-right
// icon-left
// icon-feather
// fa-reorder
